// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemLoader as MuiTreeItemLoader } from '@mui/x-tree-view-pro'

const TreeItemLoader = createMuiNode(MuiTreeItemLoader)
export default TreeItemLoader
