// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemLoaderRoot as MuiTreeItemLoaderRoot } from '@mui/x-tree-view'

const TreeItemLoaderRoot = createMuiNode(MuiTreeItemLoaderRoot)
export default TreeItemLoaderRoot
