// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ToolbarRoot as MuiToolbarRoot } from '@mui/x-data-grid-premium'

const ToolbarRoot = createMuiNode(MuiToolbarRoot)
export default ToolbarRoot
