// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterPanelBase as MuiGridFilterPanelBase } from '@mui/x-data-grid'

const GridFilterPanelBase = createMuiNode(MuiGridFilterPanelBase)
export default GridFilterPanelBase
